{
 "title": "Certificates",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Certificate Ready Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "certmanager_certificate_ready_status{condition=\"True\"}",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "Certificate Expiration Date",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "certmanager_certificate_expiration_timestamp_seconds * 1000",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "Days Remaining Before Expiration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(certmanager_certificate_expiration_timestamp_seconds - time()) / 86400",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "Certificate Renewal Date",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "certmanager_certificate_renewal_timestamp_seconds * 1000",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  }
 ]
}